### ISSUE TITLE
Not working with savegames v1.6

### ISSUE THREAD

**Issue by Elrond022** [marcrobledo/savegame-editors#93]
Updated to the newest game version (1.6). Since then I am always getting the error „invalid savegame file“.

**Comment by marcrobledo** [comment]
Can you post a 1.6 savegame?

**Comment by Ninetrix** [comment]
I have the same issue. 
Here's the affected save.
[7.zip](https://github.com/marcrobledo/savegame-editors/files/3129392/7.zip)

**Comment by marcrobledo** [comment]
Fixed in ae8ac0924382039b928d2bf4affe96dfc01ed12a

**Comment by atlbrav** [comment]
https://drive.google.com/file/d/17X737WtCbh_rcSaMRyLilDF0ok5ykkmM/view?usp=sharing

I still can't edit with my saves. I am in 1.6 as well. Link to my saves are above.

Thank You

**Comment by atlbrav** [comment]
> https://drive.google.com/file/d/17X737WtCbh_rcSaMRyLilDF0ok5ykkmM/view?usp=sharing
> 
> I still can't edit with my saves. I am in 1.6 as well. Link to my saves are above.
> 
> Thank You

Disregard. I think your page was cached in my browser.
Thank You
